<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: empleado.proto

namespace GPBMetadata\Empleado;

class Empleado
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
˜
empleado.protogrpc.empleado"
Empty"
EmpleadoRequest

id (	"G
CrearEmpleadoRequest
nombre (	
puesto (	
salario ("X
ActualizarEmpleadoRequest

id (	
nombre (	
puesto (	
salario ("w
EmpleadoResponse

id (	
nombre (	
puesto (	
salario (

created_at (	

updated_at (	"J
EmpleadoListResponse2
	empleados (2.grpc.empleado.EmpleadoResponse2µ
EmpleadoServiceL
ListarEmpleados.grpc.empleado.Empty#.grpc.empleado.EmpleadoListResponseR
ObtenerEmpleado.grpc.empleado.EmpleadoRequest.grpc.empleado.EmpleadoResponseU
CrearEmpleado#.grpc.empleado.CrearEmpleadoRequest.grpc.empleado.EmpleadoResponse_
ActualizarEmpleado(.grpc.empleado.ActualizarEmpleadoRequest.grpc.empleado.EmpleadoResponseH
EliminarEmpleado.grpc.empleado.EmpleadoRequest.grpc.empleado.EmptyB\'ÊGrpc\\EmpleadoâGPBMetadata\\Empleadobproto3'
        , true);

        static::$is_initialized = true;
    }
}

