<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: empleado.proto

namespace Grpc\Empleado;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.empleado.CrearEmpleadoRequest</code>
 */
class CrearEmpleadoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string nombre = 1;</code>
     */
    protected $nombre = '';
    /**
     * Generated from protobuf field <code>string puesto = 2;</code>
     */
    protected $puesto = '';
    /**
     * Generated from protobuf field <code>double salario = 3;</code>
     */
    protected $salario = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $nombre
     *     @type string $puesto
     *     @type float $salario
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Empleado\Empleado::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string nombre = 1;</code>
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Generated from protobuf field <code>string nombre = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNombre($var)
    {
        GPBUtil::checkString($var, True);
        $this->nombre = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string puesto = 2;</code>
     * @return string
     */
    public function getPuesto()
    {
        return $this->puesto;
    }

    /**
     * Generated from protobuf field <code>string puesto = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPuesto($var)
    {
        GPBUtil::checkString($var, True);
        $this->puesto = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double salario = 3;</code>
     * @return float
     */
    public function getSalario()
    {
        return $this->salario;
    }

    /**
     * Generated from protobuf field <code>double salario = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setSalario($var)
    {
        GPBUtil::checkDouble($var);
        $this->salario = $var;

        return $this;
    }

}

