<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/empleado.proto

namespace Grpc\Empleado;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.empleado.EmpleadoRequest</code>
 */
class EmpleadoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * El "1" no es el valor, es la posición en binario
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           El "1" no es el valor, es la posición en binario
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Empleado::initOnce();
        parent::__construct($data);
    }

    /**
     * El "1" no es el valor, es la posición en binario
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * El "1" no es el valor, es la posición en binario
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

