<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: empleado.proto

namespace Grpc\Empleado;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.empleado.EmpleadoListResponse</code>
 */
class EmpleadoListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .grpc.empleado.EmpleadoResponse empleados = 1;</code>
     */
    private $empleados;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Grpc\Empleado\EmpleadoResponse>|\Google\Protobuf\Internal\RepeatedField $empleados
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Empleado\Empleado::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .grpc.empleado.EmpleadoResponse empleados = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmpleados()
    {
        return $this->empleados;
    }

    /**
     * Generated from protobuf field <code>repeated .grpc.empleado.EmpleadoResponse empleados = 1;</code>
     * @param array<\Grpc\Empleado\EmpleadoResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmpleados($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Empleado\EmpleadoResponse::class);
        $this->empleados = $arr;

        return $this;
    }

}

