
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Empleado {
    id: ID!
    nombre: String!
    puesto: String!
    salario: Float!
    created_at: DateTime!
    updated_at: DateTime!
}

"2. Definimos las Consultas (Equivalente al GET)"
type Query {

    empleados: [Empleado!]! @all

    empleado(id: ID! @eq): Empleado @find
}

type Mutation {

    crearEmpleado(
        nombre: String!
        puesto: String!
        salario: Float!
    ): Empleado! @create


    actualizarEmpleado(
        id: ID!
        nombre: String
        puesto: String
        salario: Float
    ): Empleado! @update

    eliminarEmpleado(
        id: ID!
    ): Empleado @delete
}