<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/empleado.proto

namespace GPBMetadata\Grpc;

class Empleado
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ƒ
grpc/empleado.protogrpc.empleado"
EmpleadoRequest

id (	"O
EmpleadoResponse

id (	
nombre (	
puesto (	
salario (2e
EmpleadoServiceR
ObtenerEmpleado.grpc.empleado.EmpleadoRequest.grpc.empleado.EmpleadoResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

